force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Movie_API_ID__c.field-meta.xml
<CustomField>
    <fullName>Movie_API_ID__c</fullName>
    <externalId>true</externalId>
    <label>Movie API ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Showtime__c/Showtime__c.object-meta.xml
<CustomObject>
    <label>Showtime</label>
    <nameField>
        <displayFormat>SHW-{0000}</displayFormat>
        <label>Showtime Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Showtimes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Showtime__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Reserved_Seats__c.field-meta.xml
<CustomField>
    <fullName>Reserved_Seats__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Reserved Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <label>Session Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Session_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_Time__c</fullName>
    <label>Session Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Theater__c.field-meta.xml
<CustomField>
    <fullName>Theater__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Theater</label>
    <referenceTo>Theater__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Ticket_Price__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Price__c</fullName>
    <label>Ticket Price</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Total_Seats__c.field-meta.xml
<CustomField>
    <fullName>Total_Seats__c</fullName>
    <defaultValue>100</defaultValue>
    <label>Total Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Theater__c/Theater__c.object-meta.xml
<CustomObject>
    <label>Theater</label>
    <nameField>
        <label>Theater Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Theaters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Theater__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Theater__c/fields/Theater_API_ID__c.field-meta.xml
<CustomField>
    <fullName>Theater_API_ID__c</fullName>
    <externalId>true</externalId>
    <label>Theater API ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestHelper.cls
/**
 * @description TestHelper utility class following Context7 Apex Recipes patterns
 * @author Based on Apex Recipes TestHelper implementation
 * @date 2025-01-27
 */
@isTest
public class TestHelper {
  /**
   * @description Get the class name of an object as a string
   * @param obj The object to get the class name from
   * @return String The class name
   */
  public static String getClassName(Object obj) {
    return String.valueOf(obj).substring(0, String.valueOf(obj).indexOf(':'));
  }

  /**
   * @description Create test data for a given object type
   * @param objectType The API name of the object type
   * @param count Number of records to create
   * @return List<SObject> List of created records
   */
  public static List<SObject> createTestData(String objectType, Integer count) {
    List<SObject> records = new List<SObject>();
    
    for (Integer i = 0; i < count; i++) {
      SObject record = Schema.getGlobalDescribe().get(objectType).newSObject();
      
      // Set common fields based on object type
      if (objectType == 'Movie__c') {
        record.put('Name', 'Test Movie ' + i);
        record.put('Movie_API_ID__c', 'test' + i);
        record.put('Is_Active__c', true);
      } else if (objectType == 'Theater__c') {
        record.put('Name', 'Test Theater ' + i);
        record.put('Theater_API_ID__c', 'theater' + i);
        record.put('City__c', 'Test City ' + i);
        record.put('Is_Active__c', true);
      } else if (objectType == 'Showtime__c') {
        record.put('Session_Date__c', Date.today().addDays(i + 1));
        record.put('Session_Time__c', Time.newInstance(14, 30, 0, 0));
        record.put('Total_Seats__c', 100);
        record.put('Reserved_Seats__c', 0);
        record.put('Ticket_Price__c', 15.00);
        record.put('Status__c', 'Scheduled');
      }
      
      records.add(record);
    }
    
    return records;
  }

  /**
   * @description Create test data with relationships
   * @param objectType The API name of the object type
   * @param count Number of records to create
   * @param parentRecords Parent records to relate to
   * @return List<SObject> List of created records
   */
  public static List<SObject> createTestDataWithRelationships(
    String objectType, 
    Integer count, 
    List<SObject> parentRecords
  ) {
    List<SObject> records = new List<SObject>();
    
    for (Integer i = 0; i < count; i++) {
      SObject record = Schema.getGlobalDescribe().get(objectType).newSObject();
      
      // Set relationship fields
      if (objectType == 'Showtime__c' && parentRecords.size() >= 2) {
        record.put('Movie__c', parentRecords[0].Id);
        record.put('Theater__c', parentRecords[1].Id);
        record.put('Session_Date__c', Date.today().addDays(i + 1));
        record.put('Session_Time__c', Time.newInstance(14, 30, 0, 0));
        record.put('Total_Seats__c', 100);
        record.put('Reserved_Seats__c', 0);
        record.put('Ticket_Price__c', 15.00);
        record.put('Status__c', 'Scheduled');
      }
      
      records.add(record);
    }
    
    return records;
  }

  /**
   * @description Assert that a list of records has the expected size
   * @param records List of records to check
   * @param expectedSize Expected number of records
   * @param message Assertion message
   */
  public static void assertRecordCount(List<SObject> records, Integer expectedSize, String message) {
    System.assertEquals(expectedSize, records.size(), message);
  }

  /**
   * @description Assert that a record has a specific field value
   * @param record The record to check
   * @param fieldName The field name to check
   * @param expectedValue The expected value
   * @param message Assertion message
   */
  public static void assertFieldValue(SObject record, String fieldName, Object expectedValue, String message) {
    System.assertEquals(expectedValue, record.get(fieldName), message);
  }

  /**
   * @description Create a test user with specific profile
   * @param profileName The profile name
   * @param username The username
   * @return User The created user
   */
  public static User createTestUser(String profileName, String username) {
    Profile profile = [SELECT Id FROM Profile WHERE Name = :profileName LIMIT 1];
    
    User testUser = new User(
      FirstName = 'Test',
      LastName = 'User',
      Email = username + '@test.com',
      Username = username + '@test.com',
      Alias = 'test',
      TimeZoneSidKey = 'America/New_York',
      LocaleSidKey = 'en_US',
      EmailEncodingKey = 'UTF-8',
      LanguageLocaleKey = 'en_US',
      ProfileId = profile.Id
    );
    
    return testUser;
  }

  /**
   * @description Run tests as a specific user
   * @param testUser The user to run tests as
   * @param testMethod The test method to run
   */
  public static void runAsUser(User testUser, String testMethod) {
    System.runAs(testUser) {
      // This would need to be implemented based on specific test requirements
      System.debug('Running test method: ' + testMethod + ' as user: ' + testUser.Username);
    }
  }
}